name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

  +persist_docs:
    relation: true
    columns: true
  
  dbt_snowflake_monitoring:
    +database: DEV
    +schema: DBT_JSRUJANREDDYGMAILCOM
#   +enabled: "{{ (target.name == 'prod') | as_bool }}"

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
  course_advanced_dbt:
    unit_testing:
      +schema: unit_testing
      +tags: unit_testing

on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
